// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Yavsc.Models.IT.Fixing {
    using System;
    using System.Reflection;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Localization;

    public class BugResources {
        private static IStringLocalizer _localizer=null;
        static IStringLocalizer Localizer {
            get {
                if (_localizer != null) return _localizer;
                var scope = Startup.Services.GetRequiredService<IServiceScopeFactory>().CreateScope();
                var stringLocFactory = scope.ServiceProvider.GetService<IStringLocalizerFactory>();
                _localizer = stringLocFactory.Create(typeof(BugResources));
                return _localizer;
            }
        }
        
        public static string TitleTooLong {
            get {
                return Localizer["TitleTooLong"];
            }
        }
    }
}
