// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Yavsc {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class YavscLocalisation {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager(("Yavsc.Resources." + "Yavsc.YavscLocalisation"), typeof(YavscLocalisation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string About_BookAStar {
            get {
                return ResourceManager.GetString("About BookAStar", resourceCulture);
            }
        }
        
        public static string About_Message {
            get {
                return ResourceManager.GetString("About Message", resourceCulture);
            }
        }
        
        public static string access_denied {
            get {
                return ResourceManager.GetString("access denied", resourceCulture);
            }
        }
        
        public static string AcceptNotifications {
            get {
                return ResourceManager.GetString("AcceptNotifications", resourceCulture);
            }
        }
        
        public static string AcceptPublicContact {
            get {
                return ResourceManager.GetString("AcceptPublicContact", resourceCulture);
            }
        }
        
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        public static string ActivateMyProSettings {
            get {
                return ResourceManager.GetString("ActivateMyProSettings", resourceCulture);
            }
        }
        
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        public static string additionally {
            get {
                return ResourceManager.GetString("additionally", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string Allow_my_geolocatisation__nearby_the_clients {
            get {
                return ResourceManager.GetString("Allow my geolocatisation, nearby the clients", resourceCulture);
            }
        }
        
        public static string AnIMessageHasbeenSent {
            get {
                return ResourceManager.GetString("AnIMessageHasbeenSent", resourceCulture);
            }
        }
        
        public static string aprestation {
            get {
                return ResourceManager.GetString("aprestation", resourceCulture);
            }
        }
        
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        public static string AreYourSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYourSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        public static string AskForAnEstimate {
            get {
                return ResourceManager.GetString("AskForAnEstimate", resourceCulture);
            }
        }
        
        public static string AttachedFiles {
            get {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }
        
        public static string AuthenticatedOnly {
            get {
                return ResourceManager.GetString("AuthenticatedOnly", resourceCulture);
            }
        }
        
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        public static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back to List", resourceCulture);
            }
        }
        
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        public static string Bill_edition {
            get {
                return ResourceManager.GetString("Bill edition", resourceCulture);
            }
        }
        
        public static string Bill_removal {
            get {
                return ResourceManager.GetString("Bill removal", resourceCulture);
            }
        }
        
        public static string BillAccessControl {
            get {
                return ResourceManager.GetString("BillAccessControl", resourceCulture);
            }
        }
        
        public static string BillCreated {
            get {
                return ResourceManager.GetString("BillCreated", resourceCulture);
            }
        }
        
        public static string BillSourceCode {
            get {
                return ResourceManager.GetString("BillSourceCode", resourceCulture);
            }
        }
        
        public static string BillUpdated {
            get {
                return ResourceManager.GetString("BillUpdated", resourceCulture);
            }
        }
        
        public static string Blog_post_edition {
            get {
                return ResourceManager.GetString("Blog post edition", resourceCulture);
            }
        }
        
        public static string body {
            get {
                return ResourceManager.GetString("body", resourceCulture);
            }
        }
        
        public static string Book_AStar {
            get {
                return ResourceManager.GetString("Book AStar", resourceCulture);
            }
        }
        
        public static string Book_IT {
            get {
                return ResourceManager.GetString("Book IT", resourceCulture);
            }
        }
        
        public static string BookingTitleArtiste {
            get {
                return ResourceManager.GetString("BookingTitleArtiste", resourceCulture);
            }
        }
        
        public static string BookingTitle6829C {
            get {
                return ResourceManager.GetString("BookingTitle6829C", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        public static string Change_user_name_form {
            get {
                return ResourceManager.GetString("Change user name form", resourceCulture);
            }
        }
        
        public static string Change_your_account_settings {
            get {
                return ResourceManager.GetString("Change your account settings", resourceCulture);
            }
        }
        
        public static string Connect_using {
            get {
                return ResourceManager.GetString("Connect using", resourceCulture);
            }
        }
        
        public static string Choose_below_your_main_activity {
            get {
                return ResourceManager.GetString("Choose below your main activity", resourceCulture);
            }
        }
        
        public static string ChooseADescription {
            get {
                return ResourceManager.GetString("ChooseADescription", resourceCulture);
            }
        }
        
        public static string ChooseATitle {
            get {
                return ResourceManager.GetString("ChooseATitle", resourceCulture);
            }
        }
        
        public static string ChooseADateInTheFutur {
            get {
                return ResourceManager.GetString("ChooseADateInTheFutur", resourceCulture);
            }
        }
        
        public static string ChooseAnEventDate {
            get {
                return ResourceManager.GetString("ChooseAnEventDate", resourceCulture);
            }
        }
        
        public static string Ciffer {
            get {
                return ResourceManager.GetString("Ciffer", resourceCulture);
            }
        }
        
        public static string Circles {
            get {
                return ResourceManager.GetString("Circles", resourceCulture);
            }
        }
        
        public static string Click_action {
            get {
                return ResourceManager.GetString("Click action", resourceCulture);
            }
        }
        
        public static string Click_here_to_log_in {
            get {
                return ResourceManager.GetString("Click here to log in", resourceCulture);
            }
        }
        
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        public static string Command_confirmation {
            get {
                return ResourceManager.GetString("Command confirmation", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        public static string ContactAPerformer {
            get {
                return ResourceManager.GetString("ContactAPerformer", resourceCulture);
            }
        }
        
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        public static string CouldNotConvertVToDouble {
            get {
                return ResourceManager.GetString("CouldNotConvertVToDouble", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        public static string HyperLink {
            get {
                return ResourceManager.GetString("HyperLink", resourceCulture);
            }
        }
        
        public static string Create_a_new_article {
            get {
                return ResourceManager.GetString("Create a new article", resourceCulture);
            }
        }
        
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        public static string Date_search {
            get {
                return ResourceManager.GetString("Date search", resourceCulture);
            }
        }
        
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        public static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        public static string Defris {
            get {
                return ResourceManager.GetString("Defris", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string DoAnEstimate {
            get {
                return ResourceManager.GetString("DoAnEstimate", resourceCulture);
            }
        }
        
        public static string DoComment {
            get {
                return ResourceManager.GetString("DoComment", resourceCulture);
            }
        }
        
        public static string DoCommentPlaceHolder {
            get {
                return ResourceManager.GetString("DoCommentPlaceHolder", resourceCulture);
            }
        }
        
        public static string DoNotPublishMyActivity {
            get {
                return ResourceManager.GetString("DoNotPublishMyActivity", resourceCulture);
            }
        }
        
        public static string DocTemplateException {
            get {
                return ResourceManager.GetString("DocTemplateException", resourceCulture);
            }
        }
        
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        public static string DoPost {
            get {
                return ResourceManager.GetString("DoPost", resourceCulture);
            }
        }
        
        public static string DoTag {
            get {
                return ResourceManager.GetString("DoTag", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        public static string EditRelatedSkills {
            get {
                return ResourceManager.GetString("EditRelatedSkills", resourceCulture);
            }
        }
        
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        public static string Enter_your_email_ {
            get {
                return ResourceManager.GetString("Enter your email.", resourceCulture);
            }
        }
        
        public static string Enter_your_user_name_or_e_mail_ {
            get {
                return ResourceManager.GetString("Enter your user name or e-mail.", resourceCulture);
            }
        }
        
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        public static string Estimate_not_found {
            get {
                return ResourceManager.GetString("Estimate_not_found", resourceCulture);
            }
        }
        
        public static string EstimateToProduce {
            get {
                return ResourceManager.GetString("EstimateToProduce", resourceCulture);
            }
        }
        
        public static string EstimateToSignAsPro {
            get {
                return ResourceManager.GetString("EstimateToSignAsPro", resourceCulture);
            }
        }
        
        public static string EstimateToSignAsCli {
            get {
                return ResourceManager.GetString("EstimateToSignAsCli", resourceCulture);
            }
        }
        
        public static string EstimationMessageToClient {
            get {
                return ResourceManager.GetString("EstimationMessageToClient", resourceCulture);
            }
        }
        
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        public static string BillToSignAsPro {
            get {
                return ResourceManager.GetString("BillToSignAsPro", resourceCulture);
            }
        }
        
        public static string BillToSignAsCli {
            get {
                return ResourceManager.GetString("BillToSignAsCli", resourceCulture);
            }
        }
        
        public static string EstimateWanted {
            get {
                return ResourceManager.GetString("EstimateWanted", resourceCulture);
            }
        }
        
        public static string Event_date {
            get {
                return ResourceManager.GetString("Event date", resourceCulture);
            }
        }
        
        public static string EventWebPage {
            get {
                return ResourceManager.GetString("EventWebPage", resourceCulture);
            }
        }
        
        public static string ExistantDB {
            get {
                return ResourceManager.GetString("ExistantDB", resourceCulture);
            }
        }
        
        public static string External_Logins {
            get {
                return ResourceManager.GetString("External Logins", resourceCulture);
            }
        }
        
        public static string FillInAFutureDate {
            get {
                return ResourceManager.GetString("FillInAFutureDate", resourceCulture);
            }
        }
        
        public static string Fill_in_your_Bank_Info {
            get {
                return ResourceManager.GetString("Fill in your Bank Info", resourceCulture);
            }
        }
        
        public static string Fill_in_your_book_query {
            get {
                return ResourceManager.GetString("Fill in your book query", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        public static string Forgot_Password_Confirmation_ {
            get {
                return ResourceManager.GetString("Forgot Password Confirmation.", resourceCulture);
            }
        }
        
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full name", resourceCulture);
            }
        }
        
        public static string EGCMBUTEMAIL {
            get {
                return ResourceManager.GetString("EGCMBUTEMAIL", resourceCulture);
            }
        }
        
        public static string GCM_Notifications_sent {
            get {
                return ResourceManager.GetString("GCM Notifications sent", resourceCulture);
            }
        }
        
        public static string GCM_Notification_sending_failed {
            get {
                return ResourceManager.GetString("GCM Notification sending failed", resourceCulture);
            }
        }
        
        public static string GiveAnExplicitReason {
            get {
                return ResourceManager.GetString("GiveAnExplicitReason", resourceCulture);
            }
        }
        
        public static string GoogleDidntGeoLocalized {
            get {
                return ResourceManager.GetString("GoogleDidntGeoLocalized", resourceCulture);
            }
        }
        
        public static string Google_calendar {
            get {
                return ResourceManager.GetString("Google calendar", resourceCulture);
            }
        }
        
        public static string Google_error {
            get {
                return ResourceManager.GetString("Google error", resourceCulture);
            }
        }
        
        public static string Google_registration_id {
            get {
                return ResourceManager.GetString("Google registration id", resourceCulture);
            }
        }
        
        public static string HalfLong {
            get {
                return ResourceManager.GetString("HalfLong", resourceCulture);
            }
        }
        
        public static string MobileHairCut {
            get {
                return ResourceManager.GetString("MobileHairCut", resourceCulture);
            }
        }
        
        public static string HairCutQuery {
            get {
                return ResourceManager.GetString("HairCutQuery", resourceCulture);
            }
        }
        
        public static string HairCutQueryValidation {
            get {
                return ResourceManager.GetString("HairCutQueryValidation", resourceCulture);
            }
        }
        
        public static string Hide_source {
            get {
                return ResourceManager.GetString("Hide source", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        public static string hidden {
            get {
                return ResourceManager.GetString("hidden", resourceCulture);
            }
        }
        
        public static string I_understood {
            get {
                return ResourceManager.GetString("I understood", resourceCulture);
            }
        }
        
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        public static string Icons_made_by {
            get {
                return ResourceManager.GetString("Icons made by", resourceCulture);
            }
        }
        
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        public static string ImgLocator {
            get {
                return ResourceManager.GetString("ImgLocator", resourceCulture);
            }
        }
        
        public static string ImportException {
            get {
                return ResourceManager.GetString("ImportException", resourceCulture);
            }
        }
        
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        public static string Invalid_company_number {
            get {
                return ResourceManager.GetString("Invalid company number", resourceCulture);
            }
        }
        
        public static string is_asking_you_for_a_date {
            get {
                return ResourceManager.GetString("is asking you for a date", resourceCulture);
            }
        }
        
        public static string is_licensed_by {
            get {
                return ResourceManager.GetString("is licensed_by", resourceCulture);
            }
        }
        
        public static string Item_added_to_basket {
            get {
                return ResourceManager.GetString("Item added to basket", resourceCulture);
            }
        }
        
        public static string Kid {
            get {
                return ResourceManager.GetString("Kid", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string LoginOrEmail {
            get {
                return ResourceManager.GetString("LoginOrEmail", resourceCulture);
            }
        }
        
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        public static string MainActivity {
            get {
                return ResourceManager.GetString("MainActivity", resourceCulture);
            }
        }
        
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        public static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        public static string ManagedSiteSkills {
            get {
                return ResourceManager.GetString("ManagedSiteSkills", resourceCulture);
            }
        }
        
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        public static string MaxDailyCost {
            get {
                return ResourceManager.GetString("MaxDailyCost", resourceCulture);
            }
        }
        
        public static string MEACode {
            get {
                return ResourceManager.GetString("MEACode", resourceCulture);
            }
        }
        
        public static string Mech {
            get {
                return ResourceManager.GetString("Mech", resourceCulture);
            }
        }
        
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        public static string Message_sent {
            get {
                return ResourceManager.GetString("Message sent", resourceCulture);
            }
        }
        
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        public static string MinDailyCost {
            get {
                return ResourceManager.GetString("MinDailyCost", resourceCulture);
            }
        }
        
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        public static string Modify_settings {
            get {
                return ResourceManager.GetString("Modify settings", resourceCulture);
            }
        }
        
        public static string My_Estimates {
            get {
                return ResourceManager.GetString("My Estimates", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Needs {
            get {
                return ResourceManager.GetString("Needs", resourceCulture);
            }
        }
        
        public static string Need {
            get {
                return ResourceManager.GetString("Need", resourceCulture);
            }
        }
        
        public static string New_user_name {
            get {
                return ResourceManager.GetString("New user name", resourceCulture);
            }
        }
        
        public static string New_Tag {
            get {
                return ResourceManager.GetString("New Tag", resourceCulture);
            }
        }
        
        public static string NewPasswordMessageSent {
            get {
                return ResourceManager.GetString("NewPasswordMessageSent", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string NoTech {
            get {
                return ResourceManager.GetString("NoTech", resourceCulture);
            }
        }
        
        public static string No_calendar_for_this_user {
            get {
                return ResourceManager.GetString("No calendar for this user", resourceCulture);
            }
        }
        
        public static string no_content {
            get {
                return ResourceManager.GetString("no content", resourceCulture);
            }
        }
        
        public static string No_deposit {
            get {
                return ResourceManager.GetString("No deposit", resourceCulture);
            }
        }
        
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        public static string Non_existent_user {
            get {
                return ResourceManager.GetString("Non existent user", resourceCulture);
            }
        }
        
        public static string NoSkillforthisactivity {
            get {
                return ResourceManager.GetString("NoSkillforthisactivity", resourceCulture);
            }
        }
        
        public static string Not_Approuved {
            get {
                return ResourceManager.GetString("Not Approuved", resourceCulture);
            }
        }
        
        public static string NonValidee {
            get {
                return ResourceManager.GetString("NonValidee", resourceCulture);
            }
        }
        
        public static string NonValide {
            get {
                return ResourceManager.GetString("NonValide", resourceCulture);
            }
        }
        
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string OnlyAuthorizedMayContact {
            get {
                return ResourceManager.GetString("OnlyAuthorizedMayContact", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PaymentConfirmation {
            get {
                return ResourceManager.GetString("PaymentConfirmation", resourceCulture);
            }
        }
        
        public static string PayementsDone {
            get {
                return ResourceManager.GetString("PayementsDone", resourceCulture);
            }
        }
        
        public static string Pdf_version {
            get {
                return ResourceManager.GetString("Pdf version", resourceCulture);
            }
        }
        
        public static string PerformanceDate {
            get {
                return ResourceManager.GetString("PerformanceDate", resourceCulture);
            }
        }
        
        public static string PerformancePlace {
            get {
                return ResourceManager.GetString("PerformancePlace", resourceCulture);
            }
        }
        
        public static string Performers {
            get {
                return ResourceManager.GetString("Performers", resourceCulture);
            }
        }
        
        public static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        public static string PerformerProfile {
            get {
                return ResourceManager.GetString("PerformerProfile", resourceCulture);
            }
        }
        
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        public static string PhotoUpdated {
            get {
                return ResourceManager.GetString("PhotoUpdated", resourceCulture);
            }
        }
        
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        public static string PleaseCheckYourEmail {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmail", resourceCulture);
            }
        }
        
        public static string PleaseConfirmYourNewPassword {
            get {
                return ResourceManager.GetString("PleaseConfirmYourNewPassword", resourceCulture);
            }
        }
        
        public static string PleaseFillInABody {
            get {
                return ResourceManager.GetString("PleaseFillInABody", resourceCulture);
            }
        }
        
        public static string PleaseFillInAReason {
            get {
                return ResourceManager.GetString("PleaseFillInAReason", resourceCulture);
            }
        }
        
        public static string Please_reset_your_password_by_following_this_link_ {
            get {
                return ResourceManager.GetString("Please reset your password by following this link:", resourceCulture);
            }
        }
        
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        public static string PreferedDate {
            get {
                return ResourceManager.GetString("PreferedDate", resourceCulture);
            }
        }
        
        public static string PresationLocation {
            get {
                return ResourceManager.GetString("PresationLocation", resourceCulture);
            }
        }
        
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        public static string Previsional {
            get {
                return ResourceManager.GetString("Previsional", resourceCulture);
            }
        }
        
        public static string Profile_edition {
            get {
                return ResourceManager.GetString("Profile edition", resourceCulture);
            }
        }
        
        public static string Product_reference {
            get {
                return ResourceManager.GetString("Product reference", resourceCulture);
            }
        }
        
        public static string prestation {
            get {
                return ResourceManager.GetString("prestation", resourceCulture);
            }
        }
        
        public static string Professional_settings {
            get {
                return ResourceManager.GetString("Professional settings", resourceCulture);
            }
        }
        
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        public static string ProviderId {
            get {
                return ResourceManager.GetString("ProviderId", resourceCulture);
            }
        }
        
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        public static string RdvToPerf {
            get {
                return ResourceManager.GetString("RdvToPerf", resourceCulture);
            }
        }
        
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        public static string RegistrationUnexpectedError {
            get {
                return ResourceManager.GetString("RegistrationUnexpectedError", resourceCulture);
            }
        }
        
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string Remove_my_professional_profile {
            get {
                return ResourceManager.GetString("Remove my professional profile", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        public static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        public static string role_created {
            get {
                return ResourceManager.GetString("role created", resourceCulture);
            }
        }
        
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        public static string Save_these_settings {
            get {
                return ResourceManager.GetString("Save these settings", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Select_a_Google_calendar {
            get {
                return ResourceManager.GetString("Select a Google calendar", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string Send_a_private_message {
            get {
                return ResourceManager.GetString("Send a private message", resourceCulture);
            }
        }
        
        public static string Send_a_public_message {
            get {
                return ResourceManager.GetString("Send a public message", resourceCulture);
            }
        }
        
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        public static string SettingsClass {
            get {
                return ResourceManager.GetString("SettingsClass", resourceCulture);
            }
        }
        
        public static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        public static string Son_blog {
            get {
                return ResourceManager.GetString("Son blog", resourceCulture);
            }
        }
        
        public static string Your_performer_profile {
            get {
                return ResourceManager.GetString("Your performer profile", resourceCulture);
            }
        }
        
        public static string Setup_below_your_activity_parameters {
            get {
                return ResourceManager.GetString("Setup below your activity parameters", resourceCulture);
            }
        }
        
        public static string SiteSkills {
            get {
                return ResourceManager.GetString("SiteSkills", resourceCulture);
            }
        }
        
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        public static string SomeoneAskingYouForAnEstimate {
            get {
                return ResourceManager.GetString("SomeoneAskingYouForAnEstimate", resourceCulture);
            }
        }
        
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        public static string SpecifyLatitude {
            get {
                return ResourceManager.GetString("SpecifyLatitude", resourceCulture);
            }
        }
        
        public static string SpecifyLongitude {
            get {
                return ResourceManager.GetString("SpecifyLongitude", resourceCulture);
            }
        }
        
        public static string SpecifyPlace {
            get {
                return ResourceManager.GetString("SpecifyPlace", resourceCulture);
            }
        }
        
        public static string Specifyavalidlatitude {
            get {
                return ResourceManager.GetString("Specifyavalidlatitude", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string StartDateAfterEndDate {
            get {
                return ResourceManager.GetString("StartDateAfterEndDate", resourceCulture);
            }
        }
        
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SubmitChanges {
            get {
                return ResourceManager.GetString("SubmitChanges", resourceCulture);
            }
        }
        
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        public static string Tag_name {
            get {
                return ResourceManager.GetString("Tag name", resourceCulture);
            }
        }
        
        public static string Tex_version {
            get {
                return ResourceManager.GetString("Tex version", resourceCulture);
            }
        }
        
        public static string ThisSiteUsesCookies {
            get {
                return ResourceManager.GetString("ThisSiteUsesCookies", resourceCulture);
            }
        }
        
        public static string ThisPerformerGivesAccessToHisCalendarAndSeemsToBeAvailableThis {
            get {
                return ResourceManager.GetString("ThisPerformerGivesAccessToHisCalendarAndSeemsToBeAvailableThis", resourceCulture);
            }
        }
        
        public static string ThisPerformerGivesAccessToHisCalendarAndItAppearsHeShouldNotBeAvailableThis {
            get {
                return ResourceManager.GetString("ThisPerformerGivesAccessToHisCalendarAndItAppearsHeShouldNotBeAvailableThis", resourceCulture);
            }
        }
        
        public static string ThisPerformerDoesntGiveAccessToHisCalendar {
            get {
                return ResourceManager.GetString("ThisPerformerDoesntGiveAccessToHisCalendar", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        public static string Unitary_cost {
            get {
                return ResourceManager.GetString("Unitary_cost", resourceCulture);
            }
        }
        
        public static string Unregister {
            get {
                return ResourceManager.GetString("Unregister", resourceCulture);
            }
        }
        
        public static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use a local account to log in", resourceCulture);
            }
        }
        
        public static string Use_another_service_to_log_in {
            get {
                return ResourceManager.GetString("Use another service to log in", resourceCulture);
            }
        }
        
        public static string UseGeoLocalizationToReduceDistanceWithClients {
            get {
                return ResourceManager.GetString("UseGeoLocalizationToReduceDistanceWithClients", resourceCulture);
            }
        }
        
        public static string User_List {
            get {
                return ResourceManager.GetString("User List", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string UsersInRole {
            get {
                return ResourceManager.GetString("UsersInRole", resourceCulture);
            }
        }
        
        public static string UserSkills {
            get {
                return ResourceManager.GetString("UserSkills", resourceCulture);
            }
        }
        
        public static string UserNotInThisRole {
            get {
                return ResourceManager.GetString("UserNotInThisRole", resourceCulture);
            }
        }
        
        public static string ValidationDate {
            get {
                return ResourceManager.GetString("ValidationDate", resourceCulture);
            }
        }
        
        public static string View_source {
            get {
                return ResourceManager.GetString("View_source", resourceCulture);
            }
        }
        
        public static string was_added_to_the_role {
            get {
                return ResourceManager.GetString("was_added_to_the_role", resourceCulture);
            }
        }
        
        public static string was_added_to_the_empty_role {
            get {
                return ResourceManager.GetString("was_added_to_the_empty_role", resourceCulture);
            }
        }
        
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        public static string XHasBeenNotified {
            get {
                return ResourceManager.GetString("XHasBeenNotified", resourceCulture);
            }
        }
        
        public static string Xshouldbeavailable {
            get {
                return ResourceManager.GetString("Xshouldbeavailable", resourceCulture);
            }
        }
        
        public static string Yavsc_Models_Musical_Profiles_Instrumentation {
            get {
                return ResourceManager.GetString("Yavsc.Models.Musical.Profiles.Instrumentation", resourceCulture);
            }
        }
        
        public static string Yavsc_Models_Musical_Profiles_DjSettings {
            get {
                return ResourceManager.GetString("Yavsc.Models.Musical.Profiles.DjSettings", resourceCulture);
            }
        }
        
        public static string Yavsc_Models_Workflow_Profiles_FormationSettings {
            get {
                return ResourceManager.GetString("Yavsc.Models.Workflow.Profiles.FormationSettings", resourceCulture);
            }
        }
        
        public static string Yavsc_Models_Musical_Profiles_GeneralSettings {
            get {
                return ResourceManager.GetString("Yavsc.Models.Musical.Profiles.GeneralSettings", resourceCulture);
            }
        }
        
        public static string Yavsc_Models_Haircut_BrusherProfile {
            get {
                return ResourceManager.GetString("Yavsc.Models.Haircut.BrusherProfile", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string YouNeedToBeAuthenticatedIOToContact {
            get {
                return ResourceManager.GetString("YouNeedToBeAuthenticatedIOToContact", resourceCulture);
            }
        }
        
        public static string younotadmin {
            get {
                return ResourceManager.GetString("younotadmin", resourceCulture);
            }
        }
        
        public static string Your_account_settings {
            get {
                return ResourceManager.GetString("Your account settings", resourceCulture);
            }
        }
        
        public static string Your_book_query {
            get {
                return ResourceManager.GetString("Your book query", resourceCulture);
            }
        }
        
        public static string Your_password_has_been_reset_ {
            get {
                return ResourceManager.GetString("Your password has been reset.", resourceCulture);
            }
        }
        
        public static string YourEstimates {
            get {
                return ResourceManager.GetString("YourEstimates", resourceCulture);
            }
        }
        
        public static string YourMEACode {
            get {
                return ResourceManager.GetString("YourMEACode", resourceCulture);
            }
        }
        
        public static string YourNeed {
            get {
                return ResourceManager.GetString("YourNeed", resourceCulture);
            }
        }
        
        public static string yourquerytransmitted {
            get {
                return ResourceManager.GetString("yourquerytransmitted", resourceCulture);
            }
        }
        
        public static string YourSkills {
            get {
                return ResourceManager.GetString("YourSkills", resourceCulture);
            }
        }
        
        public static string Your_posts {
            get {
                return ResourceManager.GetString("Your posts", resourceCulture);
            }
        }
        
        public static string Your_profile {
            get {
                return ResourceManager.GetString("Your profile", resourceCulture);
            }
        }
        
        public static string YourMessageHasBeenSent {
            get {
                return ResourceManager.GetString("YourMessageHasBeenSent", resourceCulture);
            }
        }
        
        public static string Tell_more__below__about_your_query {
            get {
                return ResourceManager.GetString("Tell more, below, about your query", resourceCulture);
            }
        }
        
        public static string UnsetActivity {
            get {
                return ResourceManager.GetString("UnsetActivity", resourceCulture);
            }
        }
        
        public static string Français {
            get {
                return ResourceManager.GetString("Français", resourceCulture);
            }
        }
        
        public static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        public static string Portugais {
            get {
                return ResourceManager.GetString("Portugais", resourceCulture);
            }
        }
        
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        public static string validationError {
            get {
                return ResourceManager.GetString("validationError", resourceCulture);
            }
        }
        
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        public static string PasswordRequiresNonLetterAndDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresNonLetterAndDigit", resourceCulture);
            }
        }
        
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        public static string PassAndConfirmDontMach {
            get {
                return ResourceManager.GetString("PassAndConfirmDontMach", resourceCulture);
            }
        }
        
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string ErrorSendingEmailForConfirm {
            get {
                return ResourceManager.GetString("ErrorSendingEmailForConfirm", resourceCulture);
            }
        }
        
        public static string EmailSentForConfirm {
            get {
                return ResourceManager.GetString("EmailSentForConfirm", resourceCulture);
            }
        }
        
        public static string ConfirmYourAccountTitle {
            get {
                return ResourceManager.GetString("ConfirmYourAccountTitle", resourceCulture);
            }
        }
        
        public static string ConfirmYourAccountBody {
            get {
                return ResourceManager.GetString("ConfirmYourAccountBody", resourceCulture);
            }
        }
        
        public static string BadStringLength {
            get {
                return ResourceManager.GetString("BadStringLength", resourceCulture);
            }
        }
        
        public static string DetailledMinMaxStringLength {
            get {
                return ResourceManager.GetString("DetailledMinMaxStringLength", resourceCulture);
            }
        }
        
        public static string DetailledMaxStringLength {
            get {
                return ResourceManager.GetString("DetailledMaxStringLength", resourceCulture);
            }
        }
        
        public static string EmailSentToPerformer {
            get {
                return ResourceManager.GetString("EmailSentToPerformer", resourceCulture);
            }
        }
        
        public static string QueryValidatedNonReg {
            get {
                return ResourceManager.GetString("QueryValidatedNonReg", resourceCulture);
            }
        }
        
        public static string QueryValidatedRegular {
            get {
                return ResourceManager.GetString("QueryValidatedRegular", resourceCulture);
            }
        }
        
        public static string AllowMonthlyEmail {
            get {
                return ResourceManager.GetString("AllowMonthlyEmail", resourceCulture);
            }
        }
        
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        public static string Enroll {
            get {
                return ResourceManager.GetString("Enroll", resourceCulture);
            }
        }
        
        public static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
    }
}
