<Project>
  <Import
    Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <!-- PostIt-product-specific versions -->
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <AvaloniaVersionBase>12.1.1</AvaloniaVersionBase>
    </PropertyGroup>
    <ItemGroup>
        <!-- Avalonia packages -->
        <!-- Important: keep version in sync! -->
        <PackageVersion Include="Avalonia" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Headless" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Headless.Xunit" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersionBase)" />

        <PackageVersion Include="Material.Avalonia" Version="3.19.0" />
        <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersionBase)" />
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />

        <PackageVersion Include="Xamarin.AndroidX.Browser" Version="1.10.0.1" />

        <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.2.0" />

        <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.10.0.1" />
        <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.10.0.1" />

        <PackageVersion Include="Xamarin.UITest" Version="4.4.2" />

        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />

    </ItemGroup>
</Project>
