// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Yavsc.Model {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Yavsc.Model.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Tex_version {
            get {
                return ResourceManager.GetString("Tex_version", resourceCulture);
            }
        }
        
        public static string Message_sent {
            get {
                return ResourceManager.GetString("Message_sent", resourceCulture);
            }
        }
        
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        public static string was_added_to_the_role {
            get {
                return ResourceManager.GetString("was_added_to_the_role", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string was_added_to_the_empty_role {
            get {
                return ResourceManager.GetString("was_added_to_the_empty_role", resourceCulture);
            }
        }
        
        public static string My_Estimates {
            get {
                return ResourceManager.GetString("My_Estimates", resourceCulture);
            }
        }
        
        public static string Google_error {
            get {
                return ResourceManager.GetString("Google_error", resourceCulture);
            }
        }
        
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        public static string DocTemplateException {
            get {
                return ResourceManager.GetString("DocTemplateException", resourceCulture);
            }
        }
        
        public static string Ciffer {
            get {
                return ResourceManager.GetString("Ciffer", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        public static string younotadmin {
            get {
                return ResourceManager.GetString("younotadmin", resourceCulture);
            }
        }
        
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        public static string Date_search {
            get {
                return ResourceManager.GetString("Date_search", resourceCulture);
            }
        }
        
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string Product_reference {
            get {
                return ResourceManager.GetString("Product_reference", resourceCulture);
            }
        }
        
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        public static string Google_calendar {
            get {
                return ResourceManager.GetString("Google_calendar", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        public static string ImgLocator {
            get {
                return ResourceManager.GetString("ImgLocator", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Pdf_version {
            get {
                return ResourceManager.GetString("Pdf_version", resourceCulture);
            }
        }
        
        public static string Unitary_cost {
            get {
                return ResourceManager.GetString("Unitary_cost", resourceCulture);
            }
        }
        
        public static string Circles {
            get {
                return ResourceManager.GetString("Circles", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        public static string Estimate_not_found {
            get {
                return ResourceManager.GetString("Estimate_not_found", resourceCulture);
            }
        }
        
        public static string ProviderId {
            get {
                return ResourceManager.GetString("ProviderId", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string Not_Approuved {
            get {
                return ResourceManager.GetString("Not Approuved", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string role_created {
            get {
                return ResourceManager.GetString("role_created", resourceCulture);
            }
        }
        
        public static string User_List {
            get {
                return ResourceManager.GetString("User List", resourceCulture);
            }
        }
        
        public static string EventWebPage {
            get {
                return ResourceManager.GetString("EventWebPage", resourceCulture);
            }
        }
        
        public static string Item_added_to_basket {
            get {
                return ResourceManager.GetString("Item_added_to_basket", resourceCulture);
            }
        }
        
        public static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
    }
}
