
// This file has been generated by the GUI designer. Do not modify.
namespace yagui
{
	public partial class Main
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action reloadAction1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview2;

		private global::Gtk.Statusbar statusbar2;

		private global::Gtk.MenuBar menubar2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget yagui.Main
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.reloadAction1 = new global::Gtk.Action("reloadAction1", global::Mono.Unix.Catalog.GetString("reload"), null, null);
			this.reloadAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("reload");
			w1.Add(this.reloadAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "yagui.Main";
			this.Title = global::Mono.Unix.Catalog.GetString("Main");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child yagui.Main.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.Name = "comboboxentry1";
			this.vbox3.Add(this.comboboxentry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.comboboxentry1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.GtkScrolledWindow.Add(this.textview2);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.statusbar2 = new global::Gtk.Statusbar();
			this.statusbar2.Name = "statusbar2";
			this.statusbar2.Spacing = 6;
			// Container child statusbar2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='reloadAction1' action='reloadAction1'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.statusbar2.Add(this.menubar2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.statusbar2[this.menubar2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add(this.statusbar2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.statusbar2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 409;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
