<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1c73094f-959f-4211-b1a1-6a69b236c283</UserSecretsId>
    <RootNamespace>Yavsc.Blogs</RootNamespace>
    <RepositoryUrl>https://github.com/pazof/yavsc</RepositoryUrl>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-beta.1+2.Branch.release-1.0.8-rc1.Sha.6e50967702ba9d310017c86a2d7ee636a9e94ada</InformationalVersion>
    <Version>1.1.0-beta.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../Yavsc.Server/Yavsc.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" />
  </ItemGroup>
</Project>