<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1c73094f-959f-4211-b1a1-6a69b236c283</UserSecretsId>
    <RootNamespace>Yavsc.Blogs</RootNamespace>
    <RepositoryUrl>https://forgejo.pschneider.fr/notazof/yavsc</RepositoryUrl>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-beta.1+177.Branch.release-1.0.8-rc7.Sha.1b237fa5404368bc891ac6c599fc3920bbf83c1c</InformationalVersion>
    <Version>1.1.0-beta.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../Yavsc.Server/Yavsc.Server.csproj" />
  </ItemGroup>
</Project>