# Please find the full example project here:
# https://gitlab.com/tobiaskoch/gitlab-ci-example-mono

# see https://hub.docker.com/_/mono/
image: mono:4.6.2.7

stages:
  - test
  - deploy

before_script:
    - . /opt/mono-4.6/mono-env
    - export GIT_SSL_NO_VERIFY=true 
    - curl --insecure -sSL https://lua.pschneider.fr/files/Paul/pub/dnx-install.sh  | bash
    - DNX_USER_HOME=`pwd -P`/dnx . ./dnx/dnvm/dnvm.sh
    - cd src/OAuth.AspNet.Token && dnu restore --ignore-failed-sources
    - cd ../OAuth.AspNet.AuthServer && dnu restore --ignore-failed-sources
    - cd ../Yavsc.Abstract && dnu restore --ignore-failed-sources
    - cd ../Yavsc.Server && dnu restore --ignore-failed-sources
    - cd ../Yavsc && dnu restore --ignore-failed-sources
    - cd ../cli && dnu restore --ignore-failed-sources
    - cd ../../test/yavscTests && dnu restore --ignore-failed-sources
    - cd ../..

after_script:

debug:
  stage: test
  script:
    - cd test/yavscTests
    - cp $TestingConfig appsettings.Testing.json
    - cp $yavsc_client_secret_json yavsc-client-secret.json
    - dnu build

non_reg:
  stage: test
  artifacts:
    paths:
      - test/yavscTests/test-results.xml
    when: always
  script:
    - cd test/yavscTests
    - ASPNET_ENV=Testing dnx test -maxthreads 1 -xml test-results.xml 

non_reg_html:
  stage: test
  artifacts:
    paths:
      - test/yavscTests/test-results.html
  script:
    - cd test/yavscTests
    - xsltproc ../../assets/dnx_xunit_to_html.xsl test-results.xml > test-results.html
  trigger:
    include:
      - artifact: test/yavscTests/test-results.xml
        job: non_reg

release:
  stage: deploy
  only:
    - vnext
  artifacts:
    paths:
      - binaries/Debug
  script:
    - make packages

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - make strip_yavscd
    - cd src/Yavsc.Abstract
    - make push NUGETSOURCE=$NUGETSOURCE NUGETSOURCEAPIKEY=$NUGETSOURCEAPIKEY
  environment:
    name: staging
    url: https://yavscpre.pschneider.fr
