language: csharp
os: linux
mono:
- beta
sudo: false
install:
- curl --insecure -sSL https://lua.pschneider.fr/files/Paul/dnx-install.sh  | bash
- DNX_USER_HOME=`pwd -P`/dnx . ./dnx/dnvm/dnvm.sh
- cd src/OAuth.AspNet.Token && dnu restore
- cd src/OAuth.AspNet.AuthServer && dnu restore
- cd src/Yavsc.Abstract && dnu restore
- cd src/Yavsc.Server && dnu restore
- cd src/Yavsc && dnu restore
script:
- "dnu build"

