language: csharp
os: linux
mono:
- beta
sudo: false
install: curl --insecure -sSL https://lua.pschneider.fr/UserFiles/Paul/dnx-install.sh  | bash && DNX_USER_HOME=`pwd -P`/dnx . ./dnx/dnvm/dnvm.sh && cd Yavsc && dnu restore
script:
- "dnu build"
