// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Yavsc.Models.Streaming {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LiveFlow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager(("Yavsc.Server.Resources." + "Yavsc.Models.Streaming.LiveFlow"), typeof(LiveFlow).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DifferedFileNameLabel {
            get {
                return ResourceManager.GetString("DifferedFileNameLabel", resourceCulture);
            }
        }
        
        public static string MediaTypeLabel {
            get {
                return ResourceManager.GetString("MediaTypeLabel", resourceCulture);
            }
        }
        
        public static string PitchLabel {
            get {
                return ResourceManager.GetString("PitchLabel", resourceCulture);
            }
        }
        
        public static string SequenceNumberLabel {
            get {
                return ResourceManager.GetString("SequenceNumberLabel", resourceCulture);
            }
        }
        
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        public static string FlowIdLabel {
            get {
                return ResourceManager.GetString("FlowIdLabel", resourceCulture);
            }
        }
        
        public static string OwnerIdLabel {
            get {
                return ResourceManager.GetString("OwnerIdLabel", resourceCulture);
            }
        }
        
        public static string OwnerLabel {
            get {
                return ResourceManager.GetString("OwnerLabel", resourceCulture);
            }
        }
    }
}
