//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZicMoove {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZicMoove.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une execution est déjà en cours.
        /// </summary>
        public static string AlreadyExecuting {
            get {
                return ResourceManager.GetString("AlreadyExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bloquer cet utilisateur.
        /// </summary>
        public static string BlockThisUser {
            get {
                return ResourceManager.GetString("BlockThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blog spot.
        /// </summary>
        public static string Blogspot {
            get {
                return ResourceManager.GetString("Blogspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler la validation.
        /// </summary>
        public static string CancelValidation {
            get {
                return ResourceManager.GetString("CancelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annonces client.
        /// </summary>
        public static string ClientAnounces {
            get {
                return ResourceManager.GetString("ClientAnounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contrats client.
        /// </summary>
        public static string CLientContracts {
            get {
                return ResourceManager.GetString("CLientContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restreindre la demande aux clients professionnels.
        /// </summary>
        public static string ClientProRequest {
            get {
                return ResourceManager.GetString("ClientProRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La création a échoué, contenu envoyé: {stringContent} @ Uri: {ControllerUri.AbsoluteUri}: Erreur : {errcontent}.
        /// </summary>
        public static string CreationFailed {
            get {
                return ResourceManager.GetString("CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décliner cette proposition (envoyer un refus, et archiver la demande).
        /// </summary>
        public static string DeclineQuery {
            get {
                return ResourceManager.GetString("DeclineQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faire un devis.
        /// </summary>
        public static string DoEstimate {
            get {
                return ResourceManager.GetString("DoEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider le devis sans signer.
        /// </summary>
        public static string DonotsignEstimate {
            get {
                return ResourceManager.GetString("DonotsignEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editer le devis.
        /// </summary>
        public static string EditEstimate {
            get {
                return ResourceManager.GetString("EditEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;accès aux données distantes.
        /// </summary>
        public static string ENoRemoteEntity {
            get {
                return ResourceManager.GetString("ENoRemoteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes de devis.
        /// </summary>
        public static string EstimateQueries {
            get {
                return ResourceManager.GetString("EstimateQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bon pour accord et execution.
        /// </summary>
        public static string EstimateSigningCaption {
            get {
                return ResourceManager.GetString("EstimateSigningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signez ici.
        /// </summary>
        public static string EstimateSigningPrompt {
            get {
                return ResourceManager.GetString("EstimateSigningPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Star.
        /// </summary>
        public static string FiveStars {
            get {
                return ResourceManager.GetString("FiveStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Célébrité.
        /// </summary>
        public static string ForStars {
            get {
                return ResourceManager.GetString("ForStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Géographiquement proche.
        /// </summary>
        public static string GeographicalyNear {
            get {
                return ResourceManager.GetString("GeographicalyNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur invalide.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir une valeur entre {0} et {1}..
        /// </summary>
        public static string MinMaxIntError {
            get {
                return ResourceManager.GetString("MinMaxIntError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir une description (entre {0} et {1} caractères)..
        /// </summary>
        public static string MinMaxStringValidationError {
            get {
                return ResourceManager.GetString("MinMaxStringValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de description.
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un artiste.
        /// </summary>
        public static string NoStar {
            get {
                return ResourceManager.GetString("NoStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Étoile montante.
        /// </summary>
        public static string OneStar {
            get {
                return ResourceManager.GetString("OneStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération en cours.
        /// </summary>
        public static string OperationPending {
            get {
                return ResourceManager.GetString("OperationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à oups..
        /// </summary>
        public static string oups {
            get {
                return ResourceManager.GetString("oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annonces pro.
        /// </summary>
        public static string ProAnounces {
            get {
                return ResourceManager.GetString("ProAnounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile professionnel.
        /// </summary>
        public static string Profprof {
            get {
                return ResourceManager.GetString("Profprof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contrats fournisseur.
        /// </summary>
        public static string ProviderContracts {
            get {
                return ResourceManager.GetString("ProviderContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un artiste.
        /// </summary>
        public static string SearchForAPro {
            get {
                return ResourceManager.GetString("SearchForAPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signer.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signer le devis?.
        /// </summary>
        public static string SignOrNot {
            get {
                return ResourceManager.GetString("SignOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incontournable.
        /// </summary>
        public static string ThreeStars {
            get {
                return ResourceManager.GetString("ThreeStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À ne manquer sous aucun prétexte.
        /// </summary>
        public static string TwoStars {
            get {
                return ResourceManager.GetString("TwoStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La mise à jour a échoué..
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comptes utilisateur.
        /// </summary>
        public static string UserAccounts {
            get {
                return ResourceManager.GetString("UserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir les devis validés.
        /// </summary>
        public static string ViewEstimate {
            get {
                return ResourceManager.GetString("ViewEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos fichiers .
        /// </summary>
        public static string YourFiles {
            get {
                return ResourceManager.GetString("YourFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre texte a été taillé car il était trop long..
        /// </summary>
        public static string YourTextWasTooLong {
            get {
                return ResourceManager.GetString("YourTextWasTooLong", resourceCulture);
            }
        }
    }
}
