<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Yavsc.cli</RootNamespace>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-beta.1+2.Branch.release-1.0.8-rc1.Sha.6e50967702ba9d310017c86a2d7ee636a9e94ada</InformationalVersion>
    <Version>1.1.0-beta.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yavsc.Abstract\Yavsc.Abstract.csproj" />
    <ProjectReference Include="..\Yavsc.Server\Yavsc.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" />
  </ItemGroup>
</Project>