<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1c73094f-959f-4211-b1a1-6a69b236c283</UserSecretsId>
    <RootNamespace>Yavsc.Api</RootNamespace>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-feat-sign-estimate.1+306.Branch.feat-sign-estimate.Sha.e9a33695b38154859729b61d1280e596f1597acf</InformationalVersion>
    <Version>1.1.0-feat-sign-estimate.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../Yavsc.Server/Yavsc.Server.csproj" />
  </ItemGroup>
</Project>