<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>fr.pschneider.postit</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0-beta.1+177.Branch.release-1.0.8-rc7.Sha.1b237fa5404368bc891ac6c599fc3920bbf83c1c</InformationalVersion>
    <Version>1.1.0-beta.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
    <PackageReference Include="Xamarin.AndroidX.Browser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PostIt\PostIt.csproj" />
  </ItemGroup>
</Project>