<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Yavsc.Api.Test</RootNamespace>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.v3.common" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yavsc.Abstract\Yavsc.Abstract.csproj" />
    <ProjectReference Include="..\Yavsc.Server\Yavsc.Server.csproj" />
    <ProjectReference Include="..\Yavsc.Api\Yavsc.Api.csproj" />
    <ProjectReference Include="..\Yavsc.Org\Yavsc.Org.csproj" />
    <ProjectReference Include="..\Yavsc.Tests.Shared\Yavsc.Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
