<%@  Page Title="Chat" Language="C#" MasterPageFile="~/Models/App.master" Inherits="System.Web.Mvc.ViewPage" %>
<asp:Content ContentPlaceHolderID="head" ID="headContent" runat="server">

<!--Reference the SignalR library. -->
    <script src="<%=Url.Content("~/Scripts/jquery.signalR-2.2.0.js")%>"></script>
    <!--Reference the autogenerated SignalR hub script. script src="/signalr/hubs" /script  -->
    <script src="<%=ViewBag.SignalRHub%>/hubs"></script>
    
</asp:Content>

<asp:Content ContentPlaceHolderID="MainContent" ID="MainContentContent" runat="server">

    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="displayname" />
        <ul id="discussion"></ul>
    </div>

        <!--Script references. -->
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
      $(function () {

     function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}



            //Set the hubs URL for the connection
            $.connection.hub.url = "<%=ViewBag.SignalRHub%>";

            // Declare a proxy to reference the hub.
            var chat = $.connection.myHub;
			// 

		// var token = getCookie('RequestVerificationToken');
		// console.log(token);
 			// $.signalR.ajaxDefaults.headers = { Authorization: "Bearer " + token };

            // Create a function that the hub can call to broadcast messages.
            chat.client.addMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));


            var send = function() {
             	// Call the Send method on the hub.
                chat.server.send($('#displayname').val(), $('#message').val());
                chat.server.authSend($('#message').val());
                // Clear text box and reset focus for next comment.

                $('#message').val('').focus();
            }

            // Set initial focus to message input box.
            $('#message').focus();

            // Send the message at pressing the Enter key
            $('#message').keydown(function(e){
            	if ( e.which == 13 ) {send();}
            });

            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(send);
            });
        });
    </script>


</asp:Content>